export type OxIconVariant = 'outline' | 'fill';

export type OxIconName =
  // UI & General
  | 'search' | 'search-fill'
  | 'home' | 'home-fill'
  | 'user' | 'user-fill'
  | 'users' | 'users-fill'
  | 'user-plus' | 'user-plus-fill'
  | 'user-minus' | 'user-minus-fill'
  | 'user-check' | 'user-check-fill'
  | 'user-x' | 'user-x-fill'
  | 'id-card' | 'id-card-fill'
  | 'settings' | 'settings-fill'
  | 'sliders' | 'sliders-fill'
  | 'filter' | 'filter-fill'
  | 'trash' | 'trash-fill'
  | 'trash-2' | 'trash-2-fill'
  | 'edit' | 'edit-fill'
  | 'edit-2'
  | 'edit-3'
  | 'copy' | 'copy-fill'
  | 'share' | 'share-fill'
  | 'share-2' | 'share-2-fill'
  | 'more-horizontal'
  | 'more-vertical'
  | 'menu'
  | 'grid' | 'grid-fill'
  | 'list'
  | 'list-check'
  | 'layers' | 'layers-fill'
  | 'tag' | 'tag-fill'
  | 'pin' | 'pin-fill'
  | 'bookmark' | 'bookmark-fill'
  | 'external-link'
  | 'link'
  | 'unlink'
  | 'mouse-pointer'
  | 'layout' | 'layout-fill'
  | 'columns'
  | 'sidebar' | 'sidebar-fill'
  | 'table' | 'table-fill'
  | 'palette' | 'palette-fill'
  | 'history'
  | 'undo'
  | 'redo'
  | 'sort'
  | 'sort-asc'
  | 'sort-desc'
  | 'printer' | 'printer-fill'
  | 'qr-code'
  | 'scan'
  | 'crosshair'
  | 'target' | 'target-fill'

  // Text & Formatting
  | 'align-left'
  | 'align-center'
  | 'align-right'
  | 'align-justify'
  | 'bold' | 'bold-fill'
  | 'italic'
  | 'underline'
  | 'type'
  | 'list-ordered'
  | 'quote' | 'quote-fill'
  | 'scissors'

  // Actions & States
  | 'plus'
  | 'minus'
  | 'x'
  | 'check'
  | 'check-circle' | 'check-circle-fill'
  | 'x-circle' | 'x-circle-fill'
  | 'plus-circle' | 'plus-circle-fill'
  | 'minus-circle' | 'minus-circle-fill'
  | 'help-circle' | 'help-circle-fill'
  | 'info' | 'info-fill'
  | 'alert-circle' | 'alert-circle-fill'
  | 'alert-triangle' | 'alert-triangle-fill'
  | 'alert-octagon' | 'alert-octagon-fill'
  | 'refresh'
  | 'refresh-cw'
  | 'refresh-ccw'
  | 'rotate-cw'
  | 'rotate-ccw'
  | 'loader'
  | 'power' | 'power-fill'
  | 'log-in'
  | 'log-out'

  // Navigation & Arrows
  | 'arrow-up'
  | 'arrow-down'
  | 'arrow-left'
  | 'arrow-right'
  | 'arrow-up-right'
  | 'arrow-down-left'
  | 'chevron-up'
  | 'chevron-down'
  | 'chevron-left'
  | 'chevron-right'
  | 'chevrons-up'
  | 'chevrons-down'
  | 'chevrons-left'
  | 'chevrons-right'
  | 'corner-down-right'
  | 'corner-up-left'
  | 'maximize'
  | 'minimize'
  | 'maximize-2'
  | 'minimize-2'
  | 'zoom-in'
  | 'zoom-out'
  | 'navigation' | 'navigation-fill'

  // Communication & Social
  | 'mail' | 'mail-fill'
  | 'inbox' | 'inbox-fill'
  | 'message-square' | 'message-square-fill'
  | 'message-circle' | 'message-circle-fill'
  | 'message-dots' | 'message-dots-fill'
  | 'send' | 'send-fill'
  | 'phone' | 'phone-fill'
  | 'phone-call'
  | 'phone-off'
  | 'bell' | 'bell-fill'
  | 'bell-off' | 'bell-off-fill'
  | 'globe' | 'globe-fill'
  | 'thumbs-up' | 'thumbs-up-fill'
  | 'thumbs-down' | 'thumbs-down-fill'
  | 'heart' | 'heart-fill'
  | 'heart-pulse' | 'heart-pulse-fill'
  | 'star' | 'star-fill'
  | 'smile' | 'smile-fill'
  | 'award' | 'award-fill'
  | 'trophy' | 'trophy-fill'
  | 'crown' | 'crown-fill'
  | 'flag' | 'flag-fill'
  | 'coffee' | 'coffee-fill'
  | 'at-sign'
  | 'hash'
  | 'life-buoy' | 'life-buoy-fill'

  // Social & Brands
  | 'facebook' | 'facebook-fill'
  | 'github' | 'github-fill'
  | 'discord' | 'discord-fill'
  | 'twitter' | 'twitter-fill'
  | 'instagram' | 'instagram-fill'
  | 'linkedin' | 'linkedin-fill'
  | 'youtube' | 'youtube-fill'
  | 'twitch' | 'twitch-fill'
  | 'tiktok' | 'tiktok-fill'
  | 'slack' | 'slack-fill'
  | 'gitlab' | 'gitlab-fill'
  | 'figma' | 'figma-fill'
  | 'dribbble' | 'dribbble-fill'
  | 'whatsapp' | 'whatsapp-fill'
  | 'telegram' | 'telegram-fill'
  | 'reddit' | 'reddit-fill'
  | 'google' | 'google-fill'
  | 'apple' | 'apple-fill'
  | 'spotify' | 'spotify-fill'

  // Files & Documents
  | 'file' | 'file-fill'
  | 'file-text' | 'file-text-fill'
  | 'file-plus' | 'file-plus-fill'
  | 'file-minus' | 'file-minus-fill'
  | 'file-check' | 'file-check-fill'
  | 'file-x' | 'file-x-fill'
  | 'file-code' | 'file-code-fill'
  | 'file-pdf' | 'file-pdf-fill'
  | 'file-spreadsheet' | 'file-spreadsheet-fill'
  | 'file-zip' | 'file-zip-fill'
  | 'folder' | 'folder-fill'
  | 'folder-plus' | 'folder-plus-fill'
  | 'folder-minus' | 'folder-minus-fill'
  | 'folder-open' | 'folder-open-fill'
  | 'archive' | 'archive-fill'
  | 'box' | 'box-fill'
  | 'download'
  | 'upload'
  | 'download-cloud'
  | 'upload-cloud'
  | 'paperclip'
  | 'save' | 'save-fill'
  | 'clipboard' | 'clipboard-fill'

  // Devices & Hardware
  | 'monitor' | 'monitor-fill'
  | 'smartphone' | 'smartphone-fill'
  | 'tablet' | 'tablet-fill'
  | 'laptop' | 'laptop-fill'
  | 'tv' | 'tv-fill'
  | 'cpu' | 'cpu-fill'
  | 'hard-drive' | 'hard-drive-fill'
  | 'server' | 'server-fill'
  | 'mouse' | 'mouse-fill'
  | 'keyboard' | 'keyboard-fill'
  | 'plug' | 'plug-fill'
  | 'wifi'
  | 'wifi-off'
  | 'bluetooth'
  | 'battery' | 'battery-fill'
  | 'battery-charging'
  | 'camera' | 'camera-fill'
  | 'camera-off'
  | 'mic' | 'mic-fill'
  | 'mic-off'
  | 'volume' | 'volume-fill'
  | 'volume-1' | 'volume-1-fill'
  | 'volume-2' | 'volume-2-fill'
  | 'volume-x' | 'volume-x-fill'

  // Media & Player
  | 'play' | 'play-fill'
  | 'play-circle' | 'play-circle-fill'
  | 'pause' | 'pause-fill'
  | 'pause-circle' | 'pause-circle-fill'
  | 'stop-circle' | 'stop-circle-fill'
  | 'skip-forward' | 'skip-forward-fill'
  | 'skip-back' | 'skip-back-fill'
  | 'fast-forward' | 'fast-forward-fill'
  | 'rewind' | 'rewind-fill'
  | 'image' | 'image-fill'
  | 'video' | 'video-fill'
  | 'video-off'
  | 'music' | 'music-fill'
  | 'headphones' | 'headphones-fill'
  | 'disc' | 'disc-fill'

  // Commerce & Finance
  | 'shopping-cart' | 'shopping-cart-fill'
  | 'shopping-bag' | 'shopping-bag-fill'
  | 'credit-card' | 'credit-card-fill'
  | 'dollar-sign'
  | 'euro'
  | 'bitcoin'
  | 'calculator' | 'calculator-fill'
  | 'ticket' | 'ticket-fill'
  | 'percent'
  | 'gift' | 'gift-fill'
  | 'package' | 'package-fill'
  | 'truck' | 'truck-fill'
  | 'briefcase' | 'briefcase-fill'
  | 'wallet' | 'wallet-fill'
  | 'receipt' | 'receipt-fill'
  | 'coins' | 'coins-fill'
  | 'banknote' | 'banknote-fill'
  | 'store' | 'store-fill'

  // Security & Time
  | 'lock' | 'lock-fill'
  | 'unlock' | 'unlock-fill'
  | 'key' | 'key-fill'
  | 'shield' | 'shield-fill'
  | 'shield-check' | 'shield-check-fill'
  | 'shield-alert' | 'shield-alert-fill'
  | 'fingerprint' | 'fingerprint-fill'
  | 'eye' | 'eye-fill'
  | 'eye-off'
  | 'calendar' | 'calendar-fill'
  | 'clock' | 'clock-fill'
  | 'watch' | 'watch-fill'
  | 'map-pin' | 'map-pin-fill'
  | 'map' | 'map-fill'
  | 'compass' | 'compass-fill'

  // Charts & Analytics
  | 'bar-chart' | 'bar-chart-fill'
  | 'bar-chart-2' | 'bar-chart-2-fill'
  | 'pie-chart' | 'pie-chart-fill'
  | 'trending-up'
  | 'trending-down'

  // Development & AI
  | 'code'
  | 'terminal'
  | 'terminal-square' | 'terminal-square-fill'
  | 'database' | 'database-fill'
  | 'bot' | 'bot-fill'
  | 'brain' | 'brain-fill'
  | 'git-branch'
  | 'git-commit'
  | 'git-merge'
  | 'git-pull-request'
  | 'command'
  | 'bug' | 'bug-fill'
  | 'sparkles' | 'sparkles-fill'
  | 'wand'

  // Transport & Travel
  | 'car' | 'car-fill'
  | 'plane' | 'plane-fill'
  | 'anchor' | 'anchor-fill'
  | 'locate' | 'locate-fill'

  // Weather & Elements
  | 'sun' | 'sun-fill'
  | 'moon' | 'moon-fill'
  | 'cloud' | 'cloud-fill'
  | 'cloud-rain' | 'cloud-rain-fill'
  | 'cloud-snow'
  | 'cloud-lightning'
  | 'zap' | 'zap-fill'
  | 'wind'
  | 'droplet' | 'droplet-fill'
  | 'flame' | 'flame-fill'
  | 'activity'
  | 'thermometer' | 'thermometer-fill'
  | 'umbrella' | 'umbrella-fill'
  | 'feather';

export type OxIconSize = 'xs' | 'sm' | 'md' | 'lg' | 'xl' | '2xl' | '3xl' | number | string;

export type OxIconColor =
  | 'primary'
  | 'secondary'
  | 'success'
  | 'danger'
  | 'warning'
  | 'info'
  | 'muted'
  | 'light'
  | 'dark'
  | 'white'
  | 'inherit'
  | string;
